version: "3"
services: 

    api-server:
        image: api-server
        restart: unless-stopped
        build: ./server/
        ports: 
            - "4040:4040"
        networks: 
            - sub-app

    react-app:
        image: react-app
        restart: unless-stopped
        build: ./client/my-app/
        stdin_open: true
        ports: 
            - "3000:3000"
           
networks: 
    sub-app:
        driver: bridge

